### PR TITLE
add :hover:only

### PR DESCRIPTION
**Pull request by rosivanov**
Hi, thanks for this plugin! Sometimes i need to keep :hover only, without :focus and  i'd like to add an exception :hover:only which prevents :focus append. Can you please consider this pr?

### CODE REVIEW

**Comment by ai** [comment]
Could you remove `package-lock.json` from PR (just push commit to branch).

I am not sure that non-standard `:only` is a good idea. Maybe we should control it by comment?

**Comment by rosivanov** [comment]
> Could you remove package-lock.json from PR (just push commit to branch).

done

**Comment by rosivanov** [comment]
> I am not sure that non-standard :only is a good idea. Maybe we should control it by comment?

Okay, can you drop an example with control via comment?

**Comment by ai** [comment]
@rosivanov 

```css
button:hover, a:hover/*only*/ {
}
```

**Comment by rosivanov** [comment]
@ai thanks, can you advise an appropriate api methods to deal with comment in selector?

**Comment by ai** [comment]
Use `rule.raws` to get selector with comments

**Pull request closed without merging**
